#!/bin/bash
# /etc/init.d/remidomo

### BEGIN INIT INFO
# Provides:          remidomo
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Remidomo service
# Description:       Runs Remidomo background service
### END INIT INFO

NAME=remidomo
DESC="Remidomo service"
PIDFILE=/var/run/$NAME.pid
LOGFILE=/tmp/$NAME.log
DAEMON=/usr/bin/remidomo.py
DAEMONARGS=""

test -f $DAEMON || exit 0

case "$1" in 
    start)
        echo "Starting $NAME"
        start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --startas $DAEMON -- $DAEMONARGS
        ;;
    stop)
        echo "Stopping $NAME"
        start-stop-daemon --stop --pidfile $PIDFILE
	rm -f $PIDFILE
        ;;
    restart)
	$0 stop
	$0 start
	;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 2
        ;;
esac

exit 0
